@url = https://organic-guacamole-4xpqj999r4j2j4qw-8080.app.github.dev

GET {{url}}/alunos

###
POST {{url}}/alunos
Content-Type: application/json

{
    "nome" : "Carlos Costa"
}

###
PUT {{url}}/alunos/3
Content-Type: application/json

{
    "nome" : "Daniel Vargas"
}

###
DELETE {{url}}/alunos/2